package net.sixik.ga_utils.javatogpu.extension;

/**
 * Stable capability identifiers for compiler and runtime extensions.
 */
public enum GpuExtensionCapability {
    IR_VALIDATION,
    DIAGNOSTIC_REPORTING,
    IR_OPTIMIZATION_PROPOSAL,
    BACKEND_LOWERING,
    BACKEND_POLICY_CONTRIBUTION,
    BACKEND_SCORE_CONTRIBUTION,
    BACKEND_DISCOVERY_CONTRIBUTION,
    BACKEND_LOWERING_HOOK,
    BACKEND_COMPILATION_HOOK,
    BACKEND_INVOCATION_HOOK,
    COMPILER_FEEDBACK,
    DEVICE_SELECTION_POLICY,
    RUNTIME_LIFECYCLE_EVENT_LISTENER,
    RUNTIME_LOGGING_SERVICE,
    RUNTIME_EQUIVALENCE_EXECUTOR,
    PROMOTION_GATE,
    BACKEND_ARTIFACT_HOOK,
    ARTIFACT_WRITER
}
