package net.sixik.ga_utils.javatogpu.runtime;

/**
 * Stable event identifiers for observable runtime and compile lifecycle steps.
 */
public enum GpuRuntimeLifecycleEventKind {
    DESCRIPTOR_DISCOVERY_STARTED,
    DESCRIPTOR_DISCOVERY_COMPLETED,
    IRGPU_LOAD_STARTED,
    IRGPU_LOAD_COMPLETED,
    VALIDATION_STARTED,
    VALIDATION_COMPLETED,
    OPTIMIZER_DISCOVERY_STARTED,
    OPTIMIZER_DISCOVERY_COMPLETED,
    OPTIMIZER_PASS_STARTED,
    OPTIMIZER_PASS_COMPLETED,
    BACKEND_LOWERER_SELECTION_STARTED,
    BACKEND_LOWERER_SELECTION_COMPLETED,
    SOURCE_SELECTION_DECIDED,
    BACKEND_COMPILATION_STARTED,
    BACKEND_COMPILATION_COMPLETED,
    COMPILER_FEEDBACK_PARSING_STARTED,
    COMPILER_FEEDBACK_PARSING_COMPLETED,
    MODULE_LOAD_STARTED,
    MODULE_LOAD_COMPLETED,
    INVOCATION_STARTED,
    INVOCATION_COMPLETED,
    FALLBACK_OR_ROLLBACK_SELECTED,
    ARTIFACT_DUMP_STARTED,
    ARTIFACT_DUMP_COMPLETED,
    RUNTIME_SHUTDOWN_STARTED,
    RUNTIME_SHUTDOWN_COMPLETED
}
